name: Exercise

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linux-cross-i686:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install dpkg
          sudo dkpg --add-architecture i386
          sudo apt-get update
          sudo apt-get install gcc-mingw-w64 wine wine32

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build and Run
        run: |
          i686-w64-mingw32-gcc -Wall -O -o main.exe main.c
          wine main.exe

  msvc:
    runs-on: windows-latest
    steps:
      - name: Add compiler to PATH
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x86

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build and Run
        run: |
          cl /W3 /GF /GA /nologo /O2 /Os /Gs /c /Fomain.o main.c
          link /out:main.exe /nologo main.o
          .\main.exe
